name: Rootfs cache

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      minimal:
       required: true
       type: string
      desktop:
       required: true
       type: string
    secrets:
      token:
        required: true
jobs:

  prepare:

    name: "Make JSON"
    if: ${{ github.repository_owner == 'armbian' }}
    runs-on: ubuntu-latest
    outputs:
      matrix:  ${{steps.json.outputs.JSON_CONTENT}}
    steps:

      - name: Checkout Armbian Framework
        uses: actions/checkout@v3.3.0
        with:
          repository: armbian/build
          ref:  main
          fetch-depth: 1
          clean: false # true is default. it *will* delete the hosts /dev if mounted inside.

      - name: "Make JSON"
        id: json
        run: |
        
          # Make a list of valid pairs from our config
          echo 'JSON_CONTENT<<EOF' >> $GITHUB_OUTPUT          
          releases=($(grep -rw config/distributions/*/support -ve 'eos' | cut -d"/" -f3 | grep -Ev "focal|buster|kinetic"))
          arch=("amd64" "armhf" "arm64" "riscv64")
          for i in ${releases[@]}; do
              for j in ${arch[@]}; do
                 runner_tags=qemu
                 [[ $j == arm64 ]] && runner_tags="ARM64, igor"
                 if ! grep -q $j config/distributions/${i}/arhitectures; then continue; fi
                 echo "{\"release\":\"${i}\",\"minimal\":\"${{ inputs.minimal }}\",\"arch\":\"$j\",\"runner_tags\":\"$runner_tags\"}"
              done
          done | jq -s >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
  Docker:

    name: "B"
    needs: [ prepare ]
    strategy:
      fail-fast: false # let other jobs try to complete if one fails
      matrix:
        include: ${{ fromJSON(needs.prepare.outputs.matrix) }}

    env:
      RELEASE:         "${{ matrix.release }}"
      MINIMAL:         "${{ matrix.minimal }}"
      ARCH:            "${{ matrix.arch }}"
      RUNNER_TAG:      "${{ matrix.runner_tag }}"

    runs-on: [ ${{ matrix.runner_tags }} ]

    steps:

      - name: Checkout Armbian Framework
        uses: actions/checkout@v3.3.0
        with:
          repository: armbian/build
          ref:  main
          fetch-depth: 1
          clean: false # true is default. it *will* delete the hosts /dev if mounted inside.
