name: Build with Docker
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      rootfsarch:
       required: true
       type: string
      branch:
       required: true
       type: string
      runner:
        required: true
        type: string
    secrets:
      GPG_KEY1:
        required: false
      GPG_PASSPHRASE1:
        required: false
      GPG_KEY2:
        required: false
      GPG_PASSPHRASE2:
        required: false
      SCRIPTS_ACCESS_TOKEN:
        required: false

jobs:
  gradle:
    strategy:
      fail-fast: false
      matrix:
        board: [uefi-x86]
        release: [focal,buster,bullseye,hirsute,jammy]
        desktop: [xfce]
    #if: ${{ github.repository_owner == 'Armbian' && github.event.workflow_run.conclusion == 'success' }} || github.event_name == 'workflow_dispatch'
    name: Variant
    runs-on: ubuntu-latest    
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: armbian/build
          path: build
          clean: true

  final:
    strategy:
      fail-fast: false
      matrix:
        board: [uefi-arm64]
        release: [focal,buster,bullseye,hirsute,jammy]
        desktop: [xfce]
    #if: ${{ github.repository_owner == 'Armbian' && github.event.workflow_run.conclusion == 'success' }} || github.event_name == 'workflow_dispatch'
    name: Variant
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: armbian/build
          path: build
          clean: true









