name: Build with Docker
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      sourcerepo:
       required: true
       type: string
      variant:
       required: true
       type: string
      runner:
        required: true
        type: string
      part:
        required: true
        type: number
      of:
        required: true
        type: number
      include:
        required: false
        type: string
      exclude:
        required: false
        type: string
      uploading:
        type: string
    secrets:
      GPG_KEY1:
        required: true
      GPG_PASSPHRASE1:
        required: true
      GPG_KEY2:
        required: true
      GPG_PASSPHRASE2:
        required: true
      SCRIPTS_ACCESS_TOKEN:
        required: true
      SSH_KEY_TORRENTS: 
        required: true
      KNOWN_HOSTS_UPLOAD:
        required: true

jobs:

  Prepare:

    name: targets
    runs-on: self-hosted
    outputs:
    
      runner:   ${{steps.list_dirs.outputs.runner}}
      board:    ${{steps.list_dirs.outputs.board}}
      release:  ${{steps.list_dirs.outputs.release}}
      variant:  ${{steps.list_dirs.outputs.variant}}
      desktop:  ${{steps.list_dirs.outputs.desktop}}
      appgroup: ${{steps.list_dirs.outputs.appgroup}}
      
    steps:

      - name: Runner cleanup
        uses: igorpecovnik/freespace@main

      - name: Check disks
        run: |
        
          df
           
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 10
          repository: armbian/build
          path: build
          clean: false

      - name: Prepare matrix
        id: list_dirs
        run: |

          CHUNK=${{ inputs.variant }} # desktop uefi-x86
          VAR=$(echo $CHUNK | cut -d":" -f1)
          ARC=$(echo $CHUNK | cut -d":" -f2)
          echo ::set-output name=board::$(echo $ARC) || true
          
          echo "$VAR $ARC"

          echo ::set-output name=release::$(for x in $(grep -rw build/config/distributions/*/ -e 'supported' | cut -d"/" -f4 | sed '/buster\|focal/d'); do echo $x; done|jq -cnR '[inputs | select(length>0)]' | jq) || true

          #echo ::set-output name=desktop::$(echo 'none' ) || true
          #echo ::set-output name=appgroup::$(echo 'none' ) || true
          
          echo ::set-output name=desktop::$(for x in $(echo "none"); do echo $x; done|jq -cnR '[inputs | select(length>0)]' | jq) || true
          echo ::set-output name=appgroup::$(for x in $(echo "none"); do echo $x; done|jq -cnR '[inputs | select(length>0)]' | jq) || true
          
          if [[ $VAR == desktop* ]]; then
          echo ::set-output name=desktop::$(for x in $(grep -rw build/config/desktop/*/environments/*/support -e 'supported'  | cut -d"/" -f6 | sort | uniq); do echo $x; done|jq -cnR '[inputs | select(length>0)]' | jq) || true
              if [[ $ARC == tinkerboard ]]; then
              echo ::set-output name=desktop::$(for x in $(find build/config/desktop/*/environments/ -mindepth 1 -maxdepth 1 -type d '!' -exec test -e "{}/only_for" ';' -print | xargs -I{} grep -rw -e 'supported' {} | cut -d"/" -f6 | sort | uniq); do echo $x; done|jq -cnR '[inputs | select(length>0)]' | jq) || true
              fi
          echo ::set-output name=appgroup::$(for x in $(seq -w 01 03); do echo $x; done|jq -cnR '[inputs | select(length>0)]' | jq) || true
          fi
          
          # passing minimal, server or desktop
          echo ::set-output name=variant::$(for x in $(echo $VAR); do echo $x; done|jq -cnR '[inputs | select(length>0)]' | jq) || true          
          
          # Let's choose runners wisely
          echo ::set-output name=runner::$(echo 'X64') || true # default
          [[ $VAR != desktop && $ARC == *arm* ]] && echo ::set-output name=runner::$(echo 'ARM64') || true
          [[ $VAR == desktop ]]  && echo ::set-output name=runner::$(echo 'small') || true
          [[ $ARC == uefi-x86 ]] && echo ::set-output name=runner::$(echo 'ubuntu-latest') || true

  image:
  
    needs: Prepare
    strategy:
      fail-fast: false
      matrix:
      
        release: ${{fromJson(needs.Prepare.outputs.release)}}
        variant: ${{fromJson(needs.Prepare.outputs.variant)}}
        desktop: ${{fromJson(needs.Prepare.outputs.desktop)}}
        appgroup: ${{fromJson(needs.Prepare.outputs.appgroup)}}

    runs-on: ["${{ needs.Prepare.outputs.runner }}"]
    steps:

      - name: Runner cleanup
        uses: igorpecovnik/freespace@main

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: armbian/build
          path: build
          clean: false

      - name: Checkout support scripts
        uses: actions/checkout@v3
        with:
          repository: armbian/scripts
          path: scripts
          clean: false

      - name: Copy templates
        run: |

          mkdir -p build/userpatches
          sudo cp scripts/configs/* build/userpatches/

      - name: Pull Docker image
        run: |

          [[ -z $(command -v docker) ]] && sudo apt-get -yy install docker containerd docker.io
          sudo docker kill $(sudo docker ps -q) 2>/dev/null || true          
          sudo docker image rm $(sudo docker images | grep -v $(cat build/VERSION | sed 's/trunk.*/trunk/')"-$(dpkg --print-architecture)" | grep armbian | awk 'NR>1 {print $3}') 2> /dev/null || true 
          sudo docker pull ghcr.io/armbian/build:$(cat build/VERSION  | cut -d"." -f1-2)"-$(dpkg --print-architecture)"

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_KEY1 }}
          passphrase: ${{ secrets.GPG_PASSPHRASE1 }}
          workdir: build
          git-user-signingkey: true

      - name: Install SSH key for storage        
        uses: shimataro/ssh-key-action@v2
        with:
        
          key: ${{ secrets.SSH_KEY_TORRENTS }}
          known_hosts: ${{ secrets.KNOWN_HOSTS_UPLOAD }}
          if_key_exists: replace

      - name: Mount upload folders
        run: |

          sudo mountpoint -q build/cache/rootfs && sudo fusermount -u build/cache/rootfs || true
          sudo rm -f build/cache/rootfs/*
          sudo apt-get -y -qq install sshfs
          sudo mkdir -p /root/.ssh/
          sudo cp ~/.ssh/* /root/.ssh/          
          sudo mkdir -p build/cache/rootfs || true
          sudo sshfs upload@users.armbian.com:/rootfs build/cache/rootfs -o IdentityFile=~/.ssh/id_rsa -o reconnect -o allow_other
          sudo df

      - name: Generate rootfs
        run: |

          if [[ $(curl -s http://ifconfig.me) == "93.103.15.56" ]]; then
             CUSTOM_UBUNTU_MIRROR="si.archive.ubuntu.com/ubuntu"
             else
             CUSTOM_UBUNTU_MIRROR="us.archive.ubuntu.com/ubuntu"
          fi

          DESKTOP_APPGROUPS=${{ matrix.appgroup }}
          case "$DESKTOP_APPGROUPS" in
          "01")
              DESKTOP_APPGROUPS_SELECTED="3dsupport"
          ;;
          
          "02")
              DESKTOP_APPGROUPS_SELECTED="3dsupport browsers"
          ;;
          "03")
          
              DESKTOP_APPGROUPS_SELECTED="3dsupport browsers chat desktop_tools editors email internet languages multimedia office programming remote_desktop"
          ;;
          
          *)
              DESKTOP_APPGROUPS_SELECTED=""
          ;;
          esac

          cd build
          BUILD_DESKTOP="no"
          BUILD_MINIMAL="no"
          DESKTOP_ENVIRONMENT="${{ matrix.desktop }}"
          [[ "${{ matrix.desktop }}" == "none" ]] && DESKTOP_ENVIRONMENT=""
          [[ -n "$DESKTOP_ENVIRONMENT" ]] && BUILD_DESKTOP="yes"
          [[ "${{ matrix.variant }}" == minimal ]] && BUILD_MINIMAL="yes"

          sudo sed -i "s/-it --rm/-i --rm/" userpatches/config-docker.conf          
          ./compile.sh docker \
          GPG_PASS="${{ secrets.GPG_PASSPHRASE1 }}" \
          BETA="no" \
          ROOT_FS_CREATE_ONLY="force" \
          RELEASE="${{ matrix.release }}" \
          KERNEL_ONLY="no" \
          SKIP_EXTERNAL_TOOLCHAINS="yes" \
          IGNORE_UPDATES="yes" \
          SYNC_CLOCK="no" \
          DESKTOP_ENVIRONMENT_CONFIG_NAME="config_base" \
          BUILD_DESKTOP="$BUILD_DESKTOP" \
          BUILD_MINIMAL="$BUILD_MINIMAL" \
          DESKTOP_ENVIRONMENT="${{ matrix.desktop }}" \
          KERNEL_CONFIGURE="no" \
          BOARD="${{ needs.Prepare.outputs.board }}" \
          OFFLINE_WORK="yes" \
          LOG_SUBPATH="debug/$BOARD" \
          BRANCH="current" \
          MAKE_FOLDERS="$MAKE_FOLDERS" \
          FORCED_MONTH_OFFSET="${FORCED_MONTH_OFFSET}" \
          IMAGE_PRESENT="no" \
          BUILD_ALL="yes" \
          USE_TORRENT="no" \
          CUSTOM_UBUNTU_MIRROR="${CUSTOM_UBUNTU_MIRROR}" \
          USE_MAINLINE_GOOGLE_MIRROR="yes" \
          REPOSITORY_INSTALL="u-boot,kernel,bsp,armbian-desktop,armbian-config,armbian-firmware" \
          DESKTOP_APPGROUPS_SELECTED="$DESKTOP_APPGROUPS_SELECTED" \
          EXPERT="yes"

      - name: Unmount folders
        run: |

          sudo mountpoint -q build/cache/rootfs && sudo fusermount -u build/cache/rootfs || true
