name: Build test images with Docker

on:

  workflow_dispatch:
  workflow_call:
    inputs:
      reference:
        required: true
        type: string
      runner:
        required: true
        type: string

jobs:  

  gradle:
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        board: [uefi-x86]
        target: ["debian:bullseye:10","debian:sid:12","ubuntu:focal:8","ubuntu:jammy:12"]
    
    name: Make
    runs-on: ubuntu-latest
    outputs:    
      release:   ${{steps.gradle.outputs.release}}
    steps:

      - name: Runner prepare
        run: |
        
          echo "start"

  make-list:
    needs: gradle
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        board: [uefi-x86]
        target: ["debian:bullseye:10","debian:sid:12","ubuntu:focal:8","ubuntu:jammy:12"]

    runs-on: qemu
    name: "Test"
    steps:

      - name: Read
        run: |

          RELEASE=$(echo ${{ matrix.target }} | cut -d":" -f2)
          echo ${{ matrix.target }}
          echo ${RELEASE}
          echo "RELEASE=$RELEASE" >> $GITHUB_ENV
          
          environments=($([[ -d build/config/desktop/${RELEASE}/environments ]] && ls -1 build/config/desktop/${RELEASE}/environments))
            for j in ${environments[@]}
            do
              echo  "${RELEASE}:$j"
            done
