name: Build list
on:
  workflow_dispatch:

jobs:

  Prepare:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'Armbian' }}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: armbian/build
          path: build
          ref: nightly

      - name: Checkout scripts
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: armbian/scripts
          path: scripts
          ref: master

      - name: Make lists
        run: |
          ls -1 build/config/boards/
          find build/config/distributions -mindepth 1 -maxdepth 1 -type d | sed 's/.*\///' 
          MATRIX=$(
          set +e          
          releases=($(find build/config/distributions -mindepth 1 -maxdepth 1 -type d | sed 's/.*\///' ))
          for i in ${releases[@]}
          do	
            environments=($([[ -d build/config/desktop/$i/environments ]] && ls -1 build/config/desktop/$i/environments))
            for j in ${environments[@]}
            do
              echo  "$i:$j"
            done
          done)
          echo $MATRIX > READ

      - name: Add
        run: |
          cd scripts
          git pull
          git add READ

      - name: Commit files
        run: |
          cd scripts
          git config --local user.email "info@armbian.com"
          git config --local user.name "Armbianworker"
          git commit --allow-empty -m "Update github actions" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: ${{ github.ref }}
