name: Build test images with Docker

on:

  workflow_dispatch:
  workflow_call:

jobs:  

  Distro:
    strategy:
      fail-fast: false
      matrix:
        board: [uefi-x86]
        target: ["debian:bullseye","debian:sid","ubuntu:focal","ubuntu:jammy"]
    
    outputs:
      desktop: ${{steps.list_dirs.outputs.desktop}}
 
    runs-on: Linux
    name: "Test"    
    steps:

      - name: Checkout Armbian build script
        uses: actions/checkout@v3
        with:
          repository: armbian/build
          path: build
          fetch-depth: '100'
          clean: false

      - name: Read
        id: list_dirs
        run: |

          RELEASE=$(echo ${{ matrix.target }} | cut -d":" -f2)
          echo ${{ matrix.target }}
          echo ${RELEASE}
          echo "RELEASE=$RELEASE" >> $GITHUB_ENV
          MATRIX=$(
          set +e
          releases=($(find build/config/distributions -mindepth 1 -maxdepth 1 -type d | sed 's/.*\///' ))
          for i in ${releases[@]}
          do
          environments=($([[ -d build/config/desktop/${i}/environments ]] && ls -1 build/config/desktop/${i}/environments))
            for j in ${environments[@]}
            do
              echo  "$i:$j"
            done
          done)
          echo ::set-output name=desktop::$(for x in $(echo "${MATRIX}"); do echo $x; done|jq -cnR '[inputs | select(length>0)]' | jq) 
          
  Desktop:
  
      needs: [ Distro ]
      runs-on: Linux
      timeout-minutes: 480
      strategy:
        max-parallel: 16
        fail-fast: false
        matrix: 
          node: ${{fromJson(needs.Distro.outputs.desktop)}}

      steps:
      
        - uses: igorpecovnik/freespace@main
