name: Build with Docker
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      sourcerepo:
       required: true
       type: string
      variant:
       required: true
       type: string
      runner:
        required: true
        type: string
      part:
        required: true
        type: number
      of:
        required: true
        type: number
      include:
        required: false
        type: string
      exclude:
        required: false
        type: string
      uploading:
        type: string
    secrets:
      GPG_KEY1:
        required: true
      GPG_PASSPHRASE1:
        required: true
      GPG_KEY2:
        required: true
      GPG_PASSPHRASE2:
        required: true
      SCRIPTS_ACCESS_TOKEN:
        required: true
      SSH_KEY_TORRENTS: 
        required: true
      KNOWN_HOSTS_UPLOAD:
        required: true

jobs:

  Prepare:

    name: targets
    runs-on: ubuntu-latest
    outputs:
      release: ${{steps.list_dirs.outputs.release}}
      variant: ${{steps.list_dirs.outputs.variant}}
      desktop: ${{steps.list_dirs.outputs.desktop}}
      runner:  ${{steps.list_dirs.outputs.runner}}
    steps:

      - name: Runner cleanup
        uses: igorpecovnik/freespace@main

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 10
          repository: armbian/build
          path: build
          clean: false

      - name: Prepare matrix
        id: list_dirs
        run: |

          # default values
          echo ::set-output name=release::$(echo '[""]' | jq) || true
          echo ::set-output name=variant::$(echo '[""]' | jq) || true
          echo ::set-output name=desktop::$(echo '[""]' | jq) || true
          echo ::set-output name=runner::$(echo '[""]' | jq) || true

          CHUNK=${{ inputs.variant }}
          VAR=$(echo $CHUNK | cut -d":" -f1)
          ARC=$(echo $CHUNK | cut -d":" -f2)
          
          echo "$VAR $ARC"

          echo ::set-output name=release::$(for x in $(grep -rw build/config/distributions/*/ -e 'supported' | cut -d"/" -f4); do echo $x; done|jq -cnR '[inputs | select(length>0)]' | jq) || true

          if [[ $VAR == desktop* ]]; then 
          echo ::set-output name=desktop::$(for x in $(find -L build/config/desktop/*/environments/*/config* -name packages 2>/dev/null | cut -d"/" -f6 | sort | uniq); do echo $x; done|jq -cnR '[inputs | select(length>0)]' | jq) || true
          #else
          #echo ::set-output name=desktop::$(for x in $(echo "cli"); do echo $x; done|jq -cnR '[inputs | select(length>0)]' | jq) || true
          fi
          
          if [[ $VAR == cli* ]]; then 
          echo ::set-output name=variant::$(for x in $(echo "cli_1 cli_2"); do echo $x; done|jq -cnR '[inputs | select(length>0)]' | jq) || true
          #else
          #echo ::set-output name=variant::$(for x in $(echo "na"); do echo $x; done|jq -cnR '[inputs | select(length>0)]' | jq) || true
          fi
          
          #[[ $VAR == cli* ]] && echo ::set-output name=desktop::$(echo '[]' | jq) || true
          #$if [[ $ARC == arm* ]] && echo ::set-output name=runner::$(echo '["ARM64" , "X64","ubuntu-latest"]' | jq) || true
          #if [[ $ARC == x86 ]] && echo ::set-output name=runner::$(echo '["X64","ubuntu-latest"]' | jq) || true
          
          
          #MATRIX="seq -w 01 10"
          #echo ::set-output name=release::$(for x in $(eval $MATRIX); do echo $x; done|jq -cnR '[inputs | select(length>0)]' | jq)
          #echo ::set-output name=variant::$(for x in $(eval $MATRIX); do echo $x; done|jq -cnR '[inputs | select(length>0)]' | jq)
          #[[ $BOARD == cli* ]] && echo ::set-output name=variant::$(echo '["minimal","server"]' | jq) || true
          runners=("small" "ubuntu-latest")
          selectedrunner=$(printf "%s\n" "${runners[@]}" | shuf -n1)
          echo ::set-output name=runner::$(for x in $(echo $selectedrunner); do echo $x; done|jq -cnR '[inputs | select(length>0)]' | jq) || true
          #echo ::set-output name=runner::$(echo '["small","ubuntu-latest"]' | jq) || true

  image:
  
    needs: Prepare
    strategy:
      fail-fast: false
      matrix:
        release: ${{fromJson(needs.Prepare.outputs.release)}}
        variant: ${{fromJson(needs.Prepare.outputs.variant)}}
        desktop: ${{fromJson(needs.Prepare.outputs.desktop)}}

    runs-on: "[ ${{fromJson(needs.Prepare.outputs.runner)}} ]"
    steps:

      - name: Runner cleanup
        uses: igorpecovnik/freespace@main

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: armbian/build
          path: build
          clean: false

      - name: Checkout support scripts
        uses: actions/checkout@v3
        with:
          repository: armbian/scripts
          path: scripts
          clean: false

      - name: Copy templates
        run: |

          mkdir -p build/userpatches
          sudo cp scripts/configs/* build/userpatches/

      - name: Copy templates
        run: |

          echo ${{ matrix.release }}
          echo ${{ matrix.variant }}
          echo ${{ matrix.desktop }}

#      - name: Pull Docker image
#        run: |
#
#          [[ -z $(command -v docker) ]] && sudo apt-get -yy install docker containerd docker.io
#          sudo docker kill $(sudo docker ps -q) 2>/dev/null || true          
#          sudo docker image rm $(sudo docker images | grep -v $(cat build/VERSION | sed 's/trunk.*/trunk/')"-$(dpkg --print-architecture)" | grep armbian | awk 'NR>1 {print $3}') 2> /dev/null || true 
#          sudo docker pull ghcr.io/armbian/build:$(cat build/VERSION  | cut -d"." -f1-2)"-$(dpkg --print-architecture)"
