name: Build with Docker
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      rootfsarch:
       required: true
       type: string
      branch:
       required: true
       type: string
      runner:
        required: true
        type: string
    secrets:
      GPG_KEY1:
        required: false
      GPG_PASSPHRASE1:
        required: false
      GPG_KEY2:
        required: false
      GPG_PASSPHRASE2:
        required: false
      SCRIPTS_ACCESS_TOKEN:
        required: false

jobs:

  Prepare:

    name: targets
    runs-on: ubuntu-latest
    #if: ${{ github.repository_owner == 'armbian' }}
    outputs:
      matrix: ${{steps.list_dirs.outputs.matrix}}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: armbian/build
          path: build
          ref: nightly
          clean: false

      - name: Prepare matrix
        id: list_dirs
        run: |

echo "${{ github.event.inputs.jobs }}"

          PREFIX="-desktop"
          if [[ "${{ github.event.inputs.branch }}" == "nightly" ]]; then
             PREFIX="-cli-beta"
          fi
          echo ::set-output name=matrix::$(for x in $(cat build/config/targets${PREFIX}.conf | grep -v "^$" | grep -v "^#" |  cut -f1 -d ' ' | uniq); do echo $x; done|jq -cnR '[inputs | select(length>0)]' | jq)
       
  gradle:
    needs: Prepare
    strategy:
      fail-fast: false
      matrix:
        node: ${{fromJson(needs.Prepare.outputs.matrix)}}

    #if: ${{ github.repository_owner == 'Armbian' && github.event.workflow_run.conclusion == 'success' }} || github.event_name == 'workflow_dispatch'
    name: Variant
    runs-on: ubuntu-latest    
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: armbian/build
          path: build
          clean: true
