
name: CI
on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Make a choice
        options:
        - test
        - avc
        
        - bananapi
        - bananapim2plus
        - bananapim2ultra
        - bananapim2zero
        - bananapim3
        - bananapim64
        - bananapipro
        - bananapir2
        - clearfogbase
        - clearfogpro
        - cubieboard
        - cubieboard2
        - cubietruck
        - cubox-i
        - espressobin
        - fe-som-rk3399
        - firefly-rk3399
        - helios4
        - helios64
        - jethubj100
        - jethubj80
        - jetson-nano
        - khadas-edge
        - khadas-vim1
        - khadas-vim2
        - khadas-vim3
        - khadas-vim3l
        - lafrite
        - lepotato
        - lime
        - lime-a10
        - lime-a64
        - lime2
        - macchiatobin-doubleshot
        - micro
        - miqi
        - nanopct4
        - nanopi-r1
        - nanopi-r2c
        - nanopi-r2s
        - nanopi-r4s
        - nanopia64
        - nanopiair
        - nanopiduo
        - nanopiduo2
        - nanopik1plus
        - nanopik2-s905
        - nanopim1
        - nanopim1plus
        - nanopim4
        - nanopim4v2
        - nanopineo
        - nanopineo2
        - nanopineo2black
        - nanopineo3
        - nanopineo4
        - nanopineocore2
        - nanopineoplus2
        - odroidc2
        - odroidc4
        - odroidhc4
        - odroidn2
        - odroidxu4
        - orangepi-r1
        - orangepi-r1plus
        - orangepi-rk3399
        - orangepi2
        - orangepi3
        - orangepi4
        - orangepilite
        - orangepilite2
        - orangepione
        - orangepioneplus
        - orangepipc
        - orangepipc2
        - orangepipcplus
        - orangepiplus
        - orangepiplus2e
        - orangepiprime
        - orangepiwin
        - orangepizero
        - orangepizero2
        - orangepizeroplus
        - orangepizeroplus2-h3
        - orangepizeroplus2-h5
        - pcduino3
        - pine64
        - pine64so
        - pinebook-a64
        - pinebook-pro
        - pinecube
        - pineh64
        - pineh64-b
        - radxa-zero
        - renegade
        - rk322x-box
        - rock-3a
        - rock64
        - rockpi-4a
        - rockpi-4b
        - rockpi-4c
        - rockpi-e
        - rockpi-n10
        - rockpro64
        - rpi4b
        - station-m1
        - station-p1
        - teres-a64
        - tinkerboard
        - tinkerboard-2
        - tritium-h3
        - tritium-h5
        - udoo
        - uefi-arm64
        - uefi-x86
        - virtual-qemu
        - xt-q8l-v10
        - z28pro
        - zeropi
