
name: Build single
on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Choose a board
        options:
        - bananapi
        - bananapim2plus
        - bananapim64
jobs:

  fake:
    runs-on: small
    name: Source changes
    if: ${{ github.repository_owner == 'Armbian' }}
    steps:
      - run: |
          echo "not empty" > changes
      - uses: actions/upload-artifact@v2
        with:
          path: changes
          name: changes
          if-no-files-found: ignore

  single:
    needs: [ fake ]
    uses: armbian/scripts/.github/workflows/build-with-docker.yml@master
