name: Ping boards
on:
  workflow_dispatch:

jobs:
  
  Build: # short name because GH will expand with the matrix values
    runs-on: igor
    timeout-minutes: 480
    strategy:
      max-parallel: 4
      fail-fast: false # let other jobs try to complete if one fails
      matrix: 
        include:
          - ip: 10.0.30.221
            name: "Banana"
          - ip: 10.0.30.241
            name: "Rpi"
    steps:
    
      - name: Install SSH key for storage
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.KEY_CI }}
          known_hosts: github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
          if_key_exists: replace
    
      - name: Ping
        run: |
          echo "Ping ${{ matrix.name }}"
          ping -w5 ${{ matrix.ip }}
          echo $?
          ssh root@10.0.30.241 "run-parts /etc/update-motd.d/"
          ssh root@${{ matrix.ip }} -o StrictHostKeyChecking=no "apt-get -y update; apt-get -y upgrade"
