name: Update DUTs and reboot
on:
  workflow_dispatch:

jobs:
  
  Test:
    runs-on: igor
    timeout-minutes: 480
    strategy:
      #max-parallel: 16
      fail-fast: false
      matrix: 
        include:
          - ip: "10.0.50.252" 
            name: "Orange Pi Zero Plus 2"
            power-socket: 6
          - ip: "10.0.30.101" 
            name: "Orange Pi Zero Plus"
            power-socket: 6
          - ip: "10.0.30.103" 
            name: "Orange Pi One"
            power-socket: 6
          - ip: "10.0.30.105" 
            name: "Cubieboard"
            power-socket: 6
          - ip: "10.0.30.107" 
            name: "Orange Pi Win"
            power-socket: 15
          - ip: "10.0.30.108" 
            name: "Orange Pi Prime"
            power-socket: 9
          - ip: "10.0.30.112" 
            name: "Orange Pi+ 2E"
            power-socket: 13
          - ip: "10.0.30.113" 
            name: "Orange Pi 3"
            power-socket: 16
          - ip: "10.0.30.115" 
            name: "Odroid XU4"
            power-socket: 66
          - ip: "10.0.30.117" 
            name: "Rockpi 4B"
            power-socket: 6
          - ip: "10.0.30.119" 
            name: "Tinkerboard"
            power-socket: 14
          - ip: "10.0.30.120" 
            name: "RockPro 64"
            power-socket: 6
          - ip: "10.0.30.121" 
            name: "Odroid C4"
            power-socket: 2
          - ip: "10.0.30.126" 
            name: "Nanopi R2S"
            power-socket: 6
          - ip: "10.0.30.134" 
            name: "Cubox i2eX/i4"            
            power-socket: 64
          - ip: "10.0.30.140" 
            name: "NanoPi Neo 2 Black"
            power-socket: 65
          - ip: "10.0.30.141" 
            name: "ZeroPi"
            power-socket: 1
          - ip: "10.0.30.144" 
            name: "Banana Pi M2U"
            power-socket: 4
          - ip: "10.0.30.150" 
            name: "Orange Pi R1"
            power-socket: 6
          - ip: "10.0.30.167" 
            name: "Cubietruck"
            power-socket: 3
          - ip: "10.0.30.169" 
            name: "Clearfog Pro"
            power-socket: 200
          - ip: "10.0.30.189"
            name: "Pine H64"
            power-socket: 21
          - ip: "10.0.30.193" 
            name: "Odroid C2"
            power-socket: 8
          - ip: "10.0.30.217" 
            name: "Odroid N2"
            power-socket: 198
          - ip: "10.0.30.219" 
            name: "Rockpi E"
            power-socket: 6
          - ip: "10.0.30.241" 
            name: "Banana Pi Pro"
            power-socket: 6
          - ip: "10.0.30.246" 
            name: "NanoPi M4"
            power-socket: 6
          - ip: "10.0.30.254" 
            name: "Orange Pi Zero"  
            power-socket: 6
          - ip: "10.0.30.170" 
            name: "Udoo Quad"  
            power-socket: 3
          - ip: "10.0.30.153" 
            name: "UEFI x86"
            power-socket: 0
    steps:
    
      - name: Install SSH key for storage
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.KEY_CI }}
          known_hosts: github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
          if_key_exists: replace

      - name: Is online?
        run: |
          server="${{ matrix.ip }}"
          if nc -z $server 22 2>/dev/null; then
            echo "$server ✓"
            echo "PROCEED=true" >> $GITHUB_ENV
          else
            echo "$server ✗ needs to be power cycled"
            ssh -o StrictHostKeyChecking=no root@10.0.40.6 "./restart ${{ matrix.power-socket }}"
          fi
    
      - name: Login
        if: ${{ env.PROCEED == 'true' }}
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ matrix.ip }} "run-parts /etc/update-motd.d/"

      - name: Updat 
        if: ${{ github.repository_owner == 'Armbian' && env.PROCEED == 'true' }}
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ matrix.ip }} "apt-get -y update; apt-get -y upgrade"

      - name: Reboot
        if: ${{ github.repository_owner == 'Armbian' && env.PROCEED == 'true' }}
        run: |
          echo "Power port ${{ matrix.power-socket }}"
          ssh -o StrictHostKeyChecking=no root@${{ matrix.ip }} "shutdown -r 1"

      - name: Sleep for 3m
        if: ${{ github.repository_owner == 'Armbian' && env.PROCEED == 'true' }}
        uses: juliangruber/sleep-action@v1
        with:
          time: 3m

      - name: Ping
        if: ${{ github.repository_owner == 'Armbian' && env.PROCEED == 'true' }}
        run: |
          echo "Ping ${{ matrix.name }}"
          ping -w5 ${{ matrix.ip }}
          echo $?
          if [[ $? -eq 0 ]]; then
          ssh -o StrictHostKeyChecking=no root@${{ matrix.ip }} "run-parts /etc/update-motd.d/"
          else
          # power cycle
          ssh -o StrictHostKeyChecking=no root@10.0.40.6 "./restart ${{ matrix.power-socket }}"
          fi
  Stop:
    runs-on: igor
    if: ${{ always() }}
    needs: Test
    steps:
    - name: Stop
      run: |
        echo "Stop"
    
