name: Ping boards
on:
  workflow_dispatch:

jobs:
  
  Build: # short name because GH will expand with the matrix values
    runs-on: igor
    timeout-minutes: 480
    strategy:
      max-parallel: 4
      fail-fast: false # let other jobs try to complete if one fails
      matrix: 
        include:
          - ip: 10.0.30.221
            name: "Banana"
          - ip: 10.0.30.241
            name: "Rpi"
    steps:
    
      - name: Install SSH key for storage
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.KEY_CI }}
          if_key_exists: replace
    
      - name: Ping
        run: |
          echo "Ping ${{ matrix.name }}"
          ping -w5 ${{ matrix.ip }}
          echo $?         
