name: Ping boards
on:
  workflow_dispatch:

jobs:
  Prepare:
    runs-on: ubuntu-20.04
    if: ${{ github.repository_owner == 'Armbian' }}
    steps:
      -
        run: |
          wget -P temp https://www.armbian.com/userdata.csv
      - name: Cache Gradle packages
        uses: actions/cache@v2
        env:
          cache-name: cache-build
        with:
          path: temp
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.run_id }}

  Build: # short name because GH will expand with the matrix values
    needs: [ Prepare ]
    runs-on: ubuntu-20.04
    timeout-minutes: 480
    strategy:
      max-parallel: 4
      fail-fast: false # let other jobs try to complete if one fails
      matrix: 
        include: # build this way: cat userdata.csv | cut -d"/" -f1 | uniq | sed 's/.*/          - board: &/'
          - "10.0.30.221":"NanoPC T4"
          - "10.0.30.241":"Banana Pi Pro"          
    steps:
      - name: Install depen
        run: sudo apt-get -y install parallel jq axel
