name: Merge branch into nightly

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string

jobs:
 
  Clean:
    name: "Cleaning ${{ inputs.runner }}"
    runs-on: ${{ inputs.runner }}
    if: ${{ github.repository_owner == 'Armbian' }}
    steps:
      - name: Fix permissions
        run: |
        
          # make sure no temporally dirs are mounted from previous runs
          while :
          do
              sudo docker volume rm $(sudo docker volume ls -q) || true
              sudo pkill compile.sh || true
              sudo pkill arm-binfmt-P || true
              sudo pkill aarch64-binfmt-P || true
              sudo pkill pixz || true
              
              if [[ $(curl -s http://ifconfig.me) == "93.103.15.56" ]]; then
                  sudo mountpoint -q build/cache/rootfs &&  sudo fusermount -u build/cache/rootfs || true
                  sudo mountpoint -q build/cache/toolchain &&  sudo fusermount -u build/cache/toolchain || true
              fi
              
              sudo mountpoint -q build/output/images && sudo fusermount -u build/output/images || true
              [[ "$(df | grep "/.tmp" | wc -l)" -eq 0 && $(sudo mountpoint -q build/output/images; echo $?) -eq 1 ]] && sudo rm -rf build/.tmp && break
              echo "Mounted temp directories. Trying to unmount."
              df | grep ".tmp" | awk '{print $6}' | xargs sudo umount 2>/dev/null || true
              sleep 3
          done
          [[ -d build/output/debug ]] && sudo rm -rf build/output/debug/* || true
          [[ -d build/.git ]] && sudo chown -R $USER:$USER build/.git || true
          [[ -d build/output/images ]] && sudo rm -rf build/output/images/* || true
