name: Sync servers

on:
  workflow_dispatch:

jobs:

  sync:
    name: "Sync servers"
    runs-on: [self-hosted, Linux, local]
    if: ${{ github.repository_owner == 'Armbian' }}
    steps:

      - name: Remove previous artefacts if any
        run: |

          sudo rm -rf changes 2>/dev/null || true

#      - name: Download changes
#        uses: actions/download-artifact@v2
#        with:
#          name: changes

#      - name: Check
#        run: |
#
#          [ -s changes ] || echo "SKIP=yes" >> $GITHUB_ENV

      - name: Install SSH key for repository
        if: ${{ env.SKIP != 'yes' }}
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.KEY_UPLOAD }}
          name: upload
          known_hosts: ${{ secrets.KNOWN_HOSTS_REPOSITORY }}
          if_key_exists: replace

      - name: Update repository
        if: ${{ env.SKIP != 'yes' }}
        run: ssh -T -i ~/.ssh/upload ${{ secrets.USER_REPOSITORY }}@${{ secrets.HOST_REPOSITORY }}
