name: Testtttt
on:
  workflow_dispatch:
 
jobs:

  start:
    name: "Test"
    runs-on: igor
    steps:
     
      - name: Collect data
        timeout-minutes: 15
        uses: armbian/actions/dut-run@main
        with:
          DUT_IP: "10.0.30.210"
          LINUXFAMILY: "current"
