name: Run them all
on:
  workflow_dispatch:
 
jobs:

  start:
    name: "Power On"
    runs-on: ubuntu-latest
    steps:
     
      - name: Enable Hetzner Virtual Machines
        uses: armbian/actions/hetzner_on@main
        with:
          machine-type: cax11
          runners-count: 3
          machine-count: 2
          key: ${{ secrets.KEY_TORRENTS }}
          known_hosts: ${{ secrets.KNOWN_HOSTS_TORRENTS }}
          hetzner_id: ${{ secrets.HETZNER_ONE }}
          github_token: ${{ secrets.TEST }}

  build:
    name: "Building"
    needs: start
    runs-on: ubuntu-latest
    steps:
     
      - name: Install Homebrew
        run: sleep 1m
 
  stop:
    name: "Power Off"
    needs: build
    runs-on: ubuntu-latest
    steps:
     
      - name: Enable Hetzner Virtual Machines
        uses: armbian/actions/hetzner_off@main
        with:
          machine-type: cax11
          runners-count: 3
          machine-count: 2
          key: ${{ secrets.KEY_TORRENTS }}
          known_hosts: ${{ secrets.KNOWN_HOSTS_TORRENTS }}
          hetzner_id: ${{ secrets.HETZNER_ONE }}
          github_token: ${{ secrets.TEST }}
