name: VPS manipulation
on:
  workflow_dispatch:
  push:

jobs:

  Prepare:

    name: Prepare
    runs-on: ubuntu-latest
    env:
      HCLOUD_TOKEN: ${{ secrets.HETZNER_ONE }}
      GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:

      - name: Install SSH key for storage
        env:
          SSH_KEY_TORRENTS: ${{ secrets.SSH_KEY_TORRENTS }}
        if: env.SSH_KEY_TORRENTS != null
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY_TORRENTS }}
          known_hosts: ${{ secrets.KNOWN_HOSTS_UPLOAD }}
          if_key_exists: replace

      - name: Install Homebrew
        run: |

          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> ${HOME}/.bash_profile
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install hcloud
          hcloud server list

      - name: Show machines
        run: |
        
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          COMMAND="git clone https://github.com/armbian/scripts; export ${GH_TOKEN} ; cd scripts/generate-runners; ./deploy.sh"
          hcloud server list
          
          SERVERS=($(hcloud server list --output columns=ipv4 | tail -1))
          for i in $SERVERS
          do
            ssh-keygen -f "$HOME/.ssh/known_hosts" -R "$i"
            ssh -o StrictHostKeyChecking=no root@$i "export $PAT; $COMMAND"
          done

      - name: Show runners
        run: |
        
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository_owner }}/os/actions/runners
