name: Maintain Runners
on:
  workflow_dispatch:
  push:

jobs:

  Prepare:

    name: Prepare
    runs-on: self-hosted
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3.3.0
        
      - name: Display
        run: |
          
          cd ..
          cd ..
          PROJECT=$(echo ${{ github.workspace }} | rev | cut -d'/' -f 1 | rev)
          sudo find $(echo ${{ github.workspace }} | rev | cut -d"/" -f3- | rev) -mindepth 1 -maxdepth 1 ! -name "_*" ! -name ${PROJECT}
