name: Maintain Runners
on:
  workflow_dispatch:

jobs:

  Prepare:

    name: Prepare
    runs-on: self-hosted
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3.3.0
        
      - name: Display
        run: |
          
          env
