
name: test
on:
  workflow_dispatch:
        
jobs:

  Prepare:
    runs-on: qemu
    name: Clean output/debs and output/debs-beta
    steps:

      - name: Runner prepare
        uses: armbian/actions/runner-prepare@main
