name: List docker images
on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  Prepare:

    if: ${{ github.repository_owner == 'Armbian' }}
    name: targets
    runs-on: small
    steps:

      - name: Runner prepare
        uses: armbian/actions/runner-prepare@main
        
      - name: get Tags
        run |
          
          GHCR_TOKEN=$(echo ${{ secrets.GITHUB_TOKEN }} | base64)
          # To list tags
          curl -H "Authorization: Bearer {GHCR_TOKEN}" https://ghcr.io/v2/USER/IMAGE/tags/list
