name: Maintain Runners
on:
  workflow_dispatch:
  push:

jobs:

  Prepare:

    name: Prepare
    runs-on: self-hosted
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3.3.0
        
      - name: Display
        run: |        
          gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /orgs/armbian/actions/runners/downloads

          # go up
          cd ../..
          # find out which this project is
          PROJECT=$(echo ${{ github.workspace }} | rev | cut -d'/' -f 1 | rev)
          # remove all
          sudo find $(echo ${{ github.workspace }} | rev | cut -d"/" -f3- | rev) -mindepth 1 -maxdepth 1 ! -name "_*" ! -name ${PROJECT}
          env
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
