name: 555

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:

  Build:
    name: Compile kernel
    runs-on: rockchip
    if: ${{ github.repository_owner == 'armbian' }}
    steps:

      - name: Checkout build repo
        uses: actions/checkout@v3
        with:
          repository: armbian/build
          ref:  main
          fetch-depth: 1
          clean: false

      - name: Get JSON file
        env:
          KEY_TORRENTS: ${{ secrets.KEY_TORRENTS }}
        if: env.KEY_TORRENTS != null
        run: |
          if ! command -v "lftp" > /dev/null 2>&1; then
             sudo apt-get -y -qq install lftp
          fi
          lftp -u upload, -e "cd json; get /tmp/armbian_maintainers.json ;bye" sftp://users.armbian.com
          cat armbian_maintainers.json | jq

      - name: Build Kernel at ${{ github.event.pull_request.head.sha }}
        id: kernel
        run: |
          mkdir -p userpatches/extensions/
          cat <<- EOF > userpatches/extensions/pull-request.sh
          function post_family_config__force_commit_for_rk3588() {
              KERNELBRANCH="commit:${{ github.event.pull_request.head.sha }}"
          }
          EOF
          bash ./compile.sh kernel \
          GITHUB_ACTIONS="" \
          SHARE_LOG="yes" \
          ARTIFACT_IGNORE_CACHE="yes" \
          BOARD="orangepi5" \
          BRANCH="legacy" \
          #ENABLE_EXTENSIONS="pull-request"
