name: Run them all
on:
  workflow_dispatch:
 
jobs:
  matrix:
    name: "Powering"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
         - Faerie
         - November
         - Raven
         - Hammer
         - Foxtrot
         - Papa
         - Chimera
         - Panther
    steps:
      - name: Install Homebrew
        run: echo
        
      - name: Enable Hetzner Virtual Machines
        uses: armbian/actions/hetzner_on@main
        with:
          machine-name: ${{ matrix.version }}
          machine-type: cax11          
          key: ${{ secrets.KEY_TORRENTS }}
          known_hosts: ${{ secrets.KNOWN_HOSTS_TORRENTS }}
