name: Testing generic trigger
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      NETBOX_TOKEN:
        required: true
      KEY_CI:
        required: true
      KEY_POWER_ON:
        required: true
      KEY_POWER_OFF:
        required: true
      USER_REPOSITORY:
        required: true
      HOST_REPOSITORY:
        required: true
      KNOWN_HOSTS_REPOSITORY:
        required: true
jobs:

  Prepare:
    name: "Power system on"
    runs-on: [self-hosted, Linux, local]
    steps:

      - name: Runner prepare
        uses: armbian/actions/runner-prepare@main

      - name: Power on
        uses: armbian/actions/triggers@main
        with:
          KEY: ${{ secrets.KEY_POWER_ON }}
          USER: ${{ secrets.USER_REPOSITORY }}
          HOST: ${{ secrets.HOST_REPOSITORY }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS_REPOSITORY }}

      - name: Power off
        uses: armbian/actions/triggers@main
        with:
          KEY: ${{ secrets.KEY_POWER_OFF }}
          USER: ${{ secrets.USER_REPOSITORY }}
          HOST: ${{ secrets.HOST_REPOSITORY }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS_REPOSITORY }}
          
      - name: Update stable repository
        uses: armbian/actions/triggers@main
        with:
          KEY: ${{ secrets.KEY_REPOSITORY }}
          USER: ${{ secrets.USER_REPOSITORY }}
          HOST: ${{ secrets.HOST_REPOSITORY }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS_REPOSITORY }}

      - name: Update beta repository
        uses: armbian/actions/triggers@main
        with:
          KEY: ${{ secrets.KEY_REPOSITORY_BETA }}
          USER: ${{ secrets.USER_REPOSITORY }}
          HOST: ${{ secrets.HOST_REPOSITORY }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS_REPOSITORY }}

      - name: Update mirrors
        uses: armbian/actions/triggers@main
        with:
          KEY: ${{ secrets.KEY_SYNC_MIRRORS }}
          USER: ${{ secrets.USER_REPOSITORY }}
          HOST: ${{ secrets.HOST_REPOSITORY }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS_REPOSITORY }}

      - name: Sync images & recreate torrents
        uses: armbian/actions/triggers@main
        with:
          KEY: ${{ secrets.KEY_RECREATE_TORRENT }}
          USER: ${{ secrets.USER_REPOSITORY }}
          HOST: ${{ secrets.HOST_REPOSITORY }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS_REPOSITORY }}

