name: Maintain Runners
on:
  workflow_dispatch:
  push:

jobs:

  Prepare:

    name: Prepare
    runs-on: clean
    steps:

      - name: Remove Docker images
        run: |
        
          sudo docker system prune -a --force
        
      - name: Remove Other projects
        run: |
        
          cd ../..
          # find out which this project is
          PROJECT=$(echo ${{ github.workspace }} | rev | cut -d'/' -f 1 | rev)
          # remove all
          sudo find $(echo ${{ github.workspace }} | rev | cut -d"/" -f3- | rev) \
          -mindepth 1 -maxdepth 1 ! -name "_*" ! -name ${PROJECT} -exec sudo rm -rf {} + || true

      - name: Update runner
        run: |
        
          yes | sudo DEBIAN_FRONTEND=noninteractive apt-get -yqq update
          yes | sudo DEBIAN_FRONTEND=noninteractive apt-get -yqq upgrade
          yes | sudo DEBIAN_FRONTEND=noninteractive apt-get -yqq autoremove
          yes | sudo DEBIAN_FRONTEND=noninteractive apt-get -yqq clean
