name: Run them all
on:
  workflow_dispatch:
 
jobs:
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
         - Faerie
         - November
         - Raven
         - Hammer
         - Foxtrot
         - Papa
         - Chimera
         - Panther
    steps:
      - name: Install Homebrew
        run: echo ${{ matrix.version }}
