name: Testtttt
on:
  workflow_dispatch:
 
jobs:

  start:
    name: "Test"
    runs-on: igor
    steps:

      - name: Install SSH key for storage
        uses: shimataro/ssh-key-action@v2.5.1
        with:
          key: ${{ secrets.KEY_CI }}
          known_hosts: github.com ssh-rsa AAAAB3Nz
          if_key_exists: replace
          
      - name: Collect data
        timeout-minutes: 15
        uses: armbian/actions/dut-run@main
        with:
          DUT_IP: "10.0.30.210"
          LINUXFAMILY: "current"
