name: Run them all
on:
  workflow_dispatch:
 
jobs:

  start:
    name: "Power On"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["Faerie","November"]
#         - Raven
#         - Hammer
#         - Foxtrot
#         - Papa
#         - Chimera
#         - Panther
    steps:
     
      - name: Install Homebrew
        run: echo
        
      - name: Enable Hetzner Virtual Machines
        uses: armbian/actions/hetzner_on@main
        with:
          machine-name: ${{ matrix.version }}
          machine-type: cax11
          runners-count: 01
          key: ${{ secrets.KEY_TORRENTS }}
          known_hosts: ${{ secrets.KNOWN_HOSTS_TORRENTS }}
          hetzner_id: ${{ secrets.HETZNER_ONE }}
          github_token: ${{ secrets.TEST }}

  build:
    name: "Building"
    needs: start
    runs-on: ubuntu-latest
    steps:
     
      - name: Install Homebrew
        run: sleep 1m
 
  stop:
    name: "Power Off"
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["Faerie","November"]
#         - Raven
#         - Hammer
#         - Foxtrot
#         - Papa
#         - Chimera
#         - Panther
    steps:
     
      - name: Install Homebrew
        run: echo
        
      - name: Enable Hetzner Virtual Machines
        uses: armbian/actions/hetzner_off@main
        with:
          machine-name: ${{ matrix.version }}
          machine-type: cax11
          runners-count: 01
          key: ${{ secrets.KEY_TORRENTS }}
          known_hosts: ${{ secrets.KNOWN_HOSTS_TORRENTS }}
          hetzner_id: ${{ secrets.HETZNER_ONE }}
          github_token: ${{ secrets.TEST }}

  cleanup:
    name: "Delete temporally runners"
    needs: stop
    runs-on: ubuntu-latest
    steps:
     
      - name: Delete runners
        run: |
        
          RUNNERS=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository_owner }}/os/actions/runners \
            | jq -r '.runners[] | .id' | xargs -n2 -d'\n' | sed -e 's/ /,/g')
          while IFS= read -r id; do
          gh api \
          --method DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository_owner }}/os/actions/runners/${id}
          done <<< $RUNNERS
