name: Maintain Runners
on:
  workflow_dispatch:
  push:

jobs:

  Prepare:

    name: Prepare
    runs-on: self-hosted
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3.3.0
        
      - name: Display
        run: |
          
          PROJECT=$(echo ${{ github.workspace }} | rev | cut -d'/' -f 1 | rev)
          echo $PROJECT
