name: Smoke tests
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      NETBOX_TOKEN:
        required: true
      KEY_CI:
        required: true
      KEY_POWER_ON:
        required: true
      KEY_POWER_OFF:
        required: true
      USER_REPOSITORY:
        required: true
      HOST_REPOSITORY:
        required: true
      KNOWN_HOSTS_REPOSITORY:
        required: true
jobs:

  Prepare:
    name: "Power system on"
    runs-on: [self-hosted, Linux, local]
    steps:

      - name: Runner prepare
        uses: armbian/actions/runner-prepare@main

      - name: Power on
        uses: armbian/actions/triggers@main
        with:
          KEY_POWER_ON: ${{ secrets.KEY_POWER_ON }}
          USER_REPOSITORY: ${{ secrets.USER_REPOSITORY }}
          HOST_REPOSITORY: ${{ secrets.HOST_REPOSITORY }}
          KNOWN_HOSTS_REPOSITORY: ${{ secrets.KNOWN_HOSTS_REPOSITORY }}
