name: VPS manipulation
on:
  workflow_dispatch:
  push:

jobs:

  Prepare:

    name: Prepare
    runs-on: ubuntu-latest
    steps:

      - name: Install Homebrew
        env:
          HCLOUD_TOKEN: ${{ secrets.HETZNER_ONE }}
        run: |
        
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> ${HOME}/.bash_profile
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install hcloud
          hcloud server list
          
      - name: Show machines
        run: |
        
          hcloud server list
