name: VPS manipulation
on:
  workflow_dispatch:
  push:

jobs:

  Prepare:

    name: Prepare
    runs-on: ubuntu-latest
    steps:

      - name: Install Homebrew
        run: |
        
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
