name: Update CDN

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      KEY_TORRENTS:
        required: true
      USER_TORRENTS:
        required: true
      KNOWN_HOSTS_TORRENTS:
        required: true

jobs:

    torrents:

      name: Update download infrastructure
      runs-on: [self-hosted, Linux, local]
      if: ${{ github.repository_owner == 'Armbian' }}
      steps:

        - name: Install SSH key for torrent

          uses: shimataro/ssh-key-action@v2
          with:
            key: ${{ secrets.KEY_TORRENTS }}
            name: id_torrent # optional
            known_hosts: ${{ secrets.KNOWN_HOSTS_TORRENTS }}
            if_key_exists: replace

        - name: Create torrents

          run: ssh -T -i ~/.ssh/id_torrent ${{ secrets.USER_TORRENTS }}@${{ secrets.HOST_TORRENTS }}
